"""empty message

Revision ID: 1d533f74b8af
Revises: 4ce2a91f5cff
Create Date: 2021-12-25 01:11:28.846548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d533f74b8af'
down_revision = '4ce2a91f5cff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image_file', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image_file')
    # ### end Alembic commands ###
