"""empty message

Revision ID: 26489682eb81
Revises: 5c33987f21ae
Create Date: 2021-12-27 22:14:32.310156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26489682eb81'
down_revision = '5c33987f21ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('paragraph',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_file', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('post_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('paragraph')
    # ### end Alembic commands ###
