"""empty message

Revision ID: 3f8bc1c1794d
Revises: 0147f881ab41
Create Date: 2021-12-24 01:33:59.624179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f8bc1c1794d'
down_revision = '0147f881ab41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('topic', sa.String(length=55), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'topic')
    # ### end Alembic commands ###
