"""empty message

Revision ID: 654e35962ada
Revises: 3f8bc1c1794d
Create Date: 2021-12-24 20:48:38.706267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '654e35962ada'
down_revision = '3f8bc1c1794d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('topic', sa.Text(), nullable=True),
    sa.Column('image_file', sa.Text(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('knowledge')
    # ### end Alembic commands ###
