"""empty message

Revision ID: 68125c72e523
Revises: 8c734ddb30e1
Create Date: 2021-12-31 03:51:33.120993

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68125c72e523'
down_revision = '8c734ddb30e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('like',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('blog', sa.Integer(), nullable=True),
    sa.Column('post', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.ForeignKeyConstraint(['blog'], ['blog.id'], ),
    sa.ForeignKeyConstraint(['post'], ['post.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('like')
    # ### end Alembic commands ###
