"""empty message

Revision ID: 86e8d7e29eee
Revises: 26489682eb81
Create Date: 2021-12-30 21:06:11.680453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86e8d7e29eee'
down_revision = '26489682eb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('penduser',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=21), nullable=True),
    sa.Column('email', sa.String(length=112), nullable=True),
    sa.Column('password', sa.String(length=211), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=21), nullable=True),
    sa.Column('email', sa.String(length=112), nullable=True),
    sa.Column('image_file', sa.String(length=211), nullable=True),
    sa.Column('password', sa.String(length=211), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=True),
    sa.Column('is_staff', sa.Boolean(), nullable=True),
    sa.Column('about', sa.String(length=552), nullable=True),
    sa.Column('facebook', sa.String(length=65), nullable=True),
    sa.Column('instagram', sa.String(length=65), nullable=True),
    sa.Column('twitter', sa.String(length=65), nullable=True),
    sa.Column('github', sa.String(length=65), nullable=True),
    sa.Column('website', sa.String(length=65), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('penduser')
    # ### end Alembic commands ###
