"""empty message

Revision ID: 8c734ddb30e1
Revises: 789258c05672
Create Date: 2021-12-31 02:21:54.534808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8c734ddb30e1'
down_revision = '789258c05672'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('author', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'blog', 'user', ['author'], ['id'])
    op.add_column('comment', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.create_foreign_key(None, 'comment', 'blog', ['blog_id'], ['id'])
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'comment', type_='foreignkey')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('comment', 'blog_id')
    op.drop_constraint(None, 'blog', type_='foreignkey')
    op.drop_column('blog', 'author')
    # ### end Alembic commands ###
