"""empty message

Revision ID: d6808924af12
Revises: 68125c72e523
Create Date: 2021-12-31 04:51:47.210190

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6808924af12'
down_revision = '68125c72e523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable='True')
    op.add_column('like', sa.Column('blog_id', sa.Integer(), nullable=True))
    op.add_column('like', sa.Column('post_id', sa.Integer(), nullable=True))
    op.drop_constraint('like_post_fkey', 'like', type_='foreignkey')
    op.drop_constraint('like_blog_fkey', 'like', type_='foreignkey')
    op.create_foreign_key(None, 'like', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'like', 'blog', ['blog_id'], ['id'])
    op.drop_column('like', 'post')
    op.drop_column('like', 'blog')
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable='True')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('post', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('like', sa.Column('blog', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('like', sa.Column('post', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.drop_constraint(None, 'like', type_='foreignkey')
    op.create_foreign_key('like_blog_fkey', 'like', 'blog', ['blog'], ['id'])
    op.create_foreign_key('like_post_fkey', 'like', 'post', ['post'], ['id'])
    op.drop_column('like', 'post_id')
    op.drop_column('like', 'blog_id')
    op.alter_column('comment', 'blog_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'post_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('comment', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blog', 'author',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
